
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - nebula

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - nebula

networks:
  nebula:
    driver: bridge
